# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=64, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=140, null=True)),
                ('retweets', models.IntegerField(blank=True, null=True)),
                ('favorites', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tweets',
                'verbose_name_plural': 'tweets',
                'managed': True,
            },
        ),
    ]
