# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={'managed': True, 'verbose_name_plural': 'tweets'},
        ),
    ]
