# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20171219_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'managed': True, 'verbose_name': 'Tweet'},
        ),
        migrations.AlterModelTable(
            name='tweet',
            table='Tweet',
        ),
    ]
