# Generated by Django 2.0 on 2018-01-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20171229_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='bootstrapped',
            field=models.BooleanField(default=False),
        ),
    ]
