# Generated by Django 2.0 on 2018-02-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_tweet_bootstrapped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('tweet_number', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
            ],
            options={
                'db_table': 'Day',
                'verbose_name': 'Day',
                'managed': True,
            },
        ),
    ]
