# Generated by Django 2.0 on 2018-02-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
