# Generated by Django 2.0 on 2018-03-12 22:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0010_auto_20180223_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationType',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('display_title', models.CharField(default='', max_length=50)),
                ('display_text', models.TextField(default='', max_length=5000)),
                ('is_previewable', models.BooleanField(default=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'Classification_Type',
                'db_table': 'Classification_Type',
            },
        ),
        migrations.CreateModel(
            name='ClassifiedDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('classification_value', models.DecimalField(decimal_places=0, max_digits=10)),
                ('amount_classified', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('classification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifiers.ClassificationType')),
            ],
            options={
                'managed': True,
                'verbose_name': 'Classified_Day',
                'db_table': 'Classified_Day',
            },
        ),
        migrations.CreateModel(
            name='ClassifiedTweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classification_value', models.DecimalField(decimal_places=0, max_digits=10)),
                ('classification_probability', models.DecimalField(db_index=True, decimal_places=9, max_digits=10)),
                ('is_training_set', models.BooleanField(default=False)),
                ('classification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifiers.ClassificationType')),
                ('tweet_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.Tweet')),
            ],
            options={
                'managed': True,
                'verbose_name': 'Classified_Tweet',
                'db_table': 'Classified_Tweet',
            },
            managers=[
                ('training_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('classification_value', models.DecimalField(decimal_places=0, max_digits=10)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('classification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifiers.ClassificationType')),
            ],
            options={
                'managed': True,
                'verbose_name': 'Label',
                'db_table': 'Label',
            },
        ),
        migrations.AlterUniqueTogether(
            name='classifiedtweet',
            unique_together={('tweet_id', 'classification_type')},
        ),
        migrations.AlterUniqueTogether(
            name='classifiedday',
            unique_together={('date', 'classification_type', 'classification_value')},
        ),
    ]
